#!/bin/bash
set -eux

chlp benchmark-start || true

# /etc/cassandra/cassandra.yaml - listen_address: 10.0.3.124
ARGS=''
KEYSPACE='Keyspace1'

ARG=`action-get operations`
if [ -n "$ARG" ]; then
    ARGS+=" -o ${ARG:-INSERT}"
fi


ARG=`action-get num-different-keys`
if [[ -n "$ARG" && "$ARG" -gt "0" ]]; then
    ARGS+=" -F $ARG"
fi

ARG=`action-get truststore`
if [ -n "$ARG" ]; then
    ARGS+=" -ts $ARG"
fi

ARG=`action-get cardinality`
if [ -n "$ARG" ]; then
    ARGS+=" -C $ARG"
fi

ARG=`action-get enable-cql`
if [ -n "$ARG" ]; then
    ARGS+=" -L"
fi

ARG=`action-get enable-cql3`
if [ -n "$ARG" ]; then
    ARGS+=" -L3"
fi

ARG=`action-get transport-factory`
if [ -n "$ARG" ]; then
    ARGS+=" -tf $ARG"
fi

ARG=`action-get skip-keys`
if [ -n "$ARG" ]; then
    ARGS+=" -N $ARG"
fi

ARG=`action-get strategy-properties`
if [ -n "$ARG" ]; then
    ARGS+=" -O $ARG"
fi

ARG=`action-get ssl-protocol`
if [ -n "$ARG" ]; then
    ARGS+=" -prtcl $ARG"
fi

ARG=`action-get compression`
if [ -n "$ARG" ]; then
    ARGS+=" -I $ARG"
fi

ARG=`action-get ciphers`
if [ -n "$ARG" ]; then
    ARGS+=" -ciphers $ARG"
fi

ARG=`action-get throttle`
if [ -n "$ARG" ] && [ "$ARG" -gt "0" ]; then
    ARGS+=" -th $ARG"
fi

ARG=`action-get keep-trying`
if [ -n "$ARG" ]; then
    ARGS+=" -K $ARG"
fi

ARG=`action-get comparator`
if [ -n "$ARG" ]; then
    ARGS+=" -U $ARG"
fi

ARG=`action-get replication-on-write`
if [ -n "$ARG" ]; then
    ARGS+=" -W"
fi

ARG=`action-get average-size`
if [ -n "$ARG" ]; then
    ARGS+=" -v"
fi

ARG=`action-get query-names`
if [ -n "$ARG" ]; then
    ARGS+=" -Q $ARG"
fi

ARG=`action-get use-prepared-statements`
if [ -n "$ARG" ]; then
    ARGS+=" -P"
fi

ARG=`action-get column-size`
if [ -n "$ARG" ]; then
    ARGS+=" -S $ARG"
fi

ARG=`action-get replication-strategy`
if [ -n "$ARG" ]; then
    ARGS+=" -R $ARG"
fi

ARG=`action-get store-type`
if [ -n "$ARG" ]; then
    ARGS+=" -st $ARG"
fi

ARG=`action-get compaction-strategy`
if [ -n "$ARG" ]; then
    ARGS+=" -Z $ARG"
fi

ARG=`action-get ssl-alg`
if [ -n "$ARG" ]; then
    ARGS+=" -alg $ARG"
fi

ARG=`action-get keys-per-call`
if [ -n "$ARG" ]; then
    ARGS+=" -g $ARG"
fi

ARG=`action-get consistency-level`
if [ -n "$ARG" ]; then
    ARGS+=" -e $ARG"
fi

ARG=`action-get native-protocol`
if [ -z "$ARG" ]  && [ "$ARG" eq "True" ]; then
    ARGS+=" --enable-native-protocol"
fi

ARG=`action-get columns`
if [ -n "$ARG" ]; then
    ARGS+=" -c $ARG"
fi

ARG=`action-get num-keys`
if [ -n "$ARG" ]; then
    ARGS+=" -n $ARG"
fi

ARG=`action-get replication-factor`
if [ -n "$ARG" ]; then
    ARGS+=" -l $ARG"
fi

ARG=`action-get keep-going`
if [ -n "$ARG" ]; then
    ARGS+=" -k"
fi

ARG=`action-get truststore-password`
if [ -n "$ARG" ]; then
    ARGS+=" -tspw $ARG"
fi

ARG=`action-get supercolumns`
if [ -n "$ARG" ]; then
    ARGS+=" -u $ARG"
fi

ARG=`action-get threads`
if [ -n "$ARG" ]; then
    ARGS+=" -t $ARG"
fi

ARG=`action-get stdev`
if [ -n "$ARG" ]; then
    ARGS+=" -s $ARG"
fi

ARG=`action-get random`
if [ -n "$ARG" ]; then
    ARGS+=" -r"
fi

ARG=`action-get family-type`
if [ -n "$ARG" ]; then
    ARGS+=" -y $ARG"
fi

ARG=`action-get create-index`
if [ -n "$ARG" ]; then
    ARGS+=" -x $ARG"
fi

NODES=`grep listen_address /etc/cassandra/cassandra.yaml | awk '{print $2}'| head -n 1`

run=`date +%s`
mkdir -p /opt/cassandra-stress/results/$run

cassandra-stress -f /opt/cassandra-stress/results/$run/stress.log -d $NODES $ARGS

# Parse the results
`cat /opt/cassandra-stress/results/$run/stress.log | python $CHARM_DIR/actions/stress2json.py`

chlp benchmark-finish || true
